export const styles = {
  container: {
    maxWidth: "800px",
    margin: "20px auto",
    padding: "20px",
    backgroundColor: "white",
    borderRadius: "8px",
    boxShadow: "0 2px 4px rgba(0, 0, 0, 0.1)",
  },
  header: {
    marginBottom: "20px",
  },
  title: {
    fontSize: "24px",
    fontWeight: "bold",
    marginBottom: "10px",
  },
  uploadContainer: {
    position: "relative",
    marginBottom: "20px",
  },
  uploadSection: {
    border: "2px dashed #ccc",
    borderRadius: "8px",
    padding: "20px",
    textAlign: "center",
    marginBottom: "20px",
    cursor: "pointer",
    minHeight: "200px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  uploadSectionWithPreview: {
    padding: "10px",
    cursor: "default",
  },
  uploadActive: {
    borderColor: "#007bff",
    backgroundColor: "#f8f9fa",
  },
  previewContainer: {
    position: "relative",
    width: "100%",
    height: "100%",
  },
  previewImage: {
    maxWidth: "100%",
    maxHeight: "300px",
    objectFit: "contain",
    borderRadius: "4px",
  },
  clearButton: {
    position: "absolute",
    top: "-10px",
    right: "-10px",
    backgroundColor: "#ff4444",
    color: "white",
    border: "none",
    borderRadius: "50%",
    width: "24px",
    height: "24px",
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    padding: "0",
    boxShadow: "0 2px 4px rgba(0,0,0,0.2)",
  },
  uploadActive: {
    borderColor: "#007bff",
    backgroundColor: "#f8f9fa",
  },
  jsonEditor: {
    marginTop: "20px",
    marginBottom: "20px",
  },
  textarea: {
    width: "100%",
    height: "200px",
    padding: "8px",
    borderRadius: "4px",
    border: "1px solid #ccc",
    fontFamily: "monospace",
  },
  button: {
    backgroundColor: "#007bff",
    color: "white",
    padding: "10px 20px",
    border: "none",
    borderRadius: "4px",
    cursor: "pointer",
    fontSize: "16px",
    width: "100%",
    marginBottom: "10px",
  },
  buttonDisabled: {
    backgroundColor: "#ccc",
    cursor: "not-allowed",
  },
  error: {
    backgroundColor: "#ffebee",
    color: "#c62828",
    padding: "10px",
    borderRadius: "4px",
    marginBottom: "10px",
  },
  imageGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(3, 1fr)",
    gap: "20px",
    marginTop: "20px",
  },
  imageContainer: {
    border: "1px solid #ddd",
    borderRadius: "8px",
    padding: "10px",
  },
  image: {
    width: "100%",
    height: "auto",
    borderRadius: "4px",
  },
  imageLabel: {
    marginTop: "8px",
    textAlign: "center",
    fontSize: "14px",
    color: "#666",
  },
  debugPanel: {
    backgroundColor: "#f8f9fa",
    padding: "12px",
    marginTop: "20px",
    borderRadius: "6px",
    fontFamily:
      "ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace",
    fontSize: "12px",
    maxHeight: "300px",
    overflowY: "auto",
    border: "1px solid #e5e7eb",
    scrollBehavior: "smooth",
    // Add custom scrollbar styling
    "&::WebkitScrollbar": {
      width: "8px",
    },
    "&::WebkitScrollbarTrack": {
      backgroundColor: "#f1f1f1",
      borderRadius: "4px",
    },
    "&::WebkitScrollbarThumb": {
      backgroundColor: "#c1c1c1",
      borderRadius: "4px",
      "&:hover": {
        backgroundColor: "#a8a8a8",
      },
    },
  },
  workflowContainer: {
    backgroundColor: "white",
    borderRadius: "8px",
    boxShadow: "0 2px 4px rgba(0, 0, 0, 0.1)",
    padding: "20px",
    marginBottom: "20px",
  },
  workflowSelectionContainer: {
    marginBottom: "20px",
  },
  workflowLabel: {
    display: "block",
    fontSize: "0.875rem",
    fontWeight: "500",
    color: "#374151",
    marginBottom: "8px",
  },
  workflowSelect: {
    width: "100%",
    padding: "8px 12px",
    borderRadius: "4px",
    border: "1px solid #d1d5db",
    backgroundColor: "white",
    fontSize: "0.875rem",
    color: "#374151",
    cursor: "pointer",
  },
  divider: {
    margin: "20px 0",
    border: "none",
    borderTop: "1px solid #e5e7eb",
  },
  debugPanelHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: "8px",
  },
  debugPanelTitle: {
    fontSize: "14px",
    fontWeight: "600",
  },
  debugPanelScrollButton: {
    fontSize: "12px",
    padding: "4px 8px",
    backgroundColor: "#e5e7eb",
    border: "none",
    borderRadius: "4px",
    cursor: "pointer",
  },
  debugLogEntry: {
    fontSize: "12px",
    color: "#4b5563",
    padding: "4px 0",
    borderBottom: "1px solid #f0f0f0",
  },
  lastDebugLogEntry: {
    borderBottom: "none",
  },
  progressContainer: {
    marginTop: "16px",
    padding: "16px",
    backgroundColor: "#f3f4f6",
    borderRadius: "8px",
  },
  progressBar: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
  },
  progressBarTrack: {
    width: "100%",
    backgroundColor: "#e5e7eb",
    borderRadius: "9999px",
    height: "10px",
  },
  progressBarFill: {
    backgroundColor: "#2563eb",
    height: "10px",
    borderRadius: "9999px",
    transition: "width 0.2s",
  },
  progressText: {
    fontSize: "14px",
    color: "#4b5563",
  },
  progressStatus: {
    fontSize: "14px",
    color: "#4b5563",
  },
  errorBoundary: {
    backgroundColor: "#fee2e2",
    border: "1px solid #fecaca",
    borderRadius: "6px",
    padding: "16px",
  },
  errorBoundaryTitle: {
    color: "#991b1b",
    fontWeight: "500",
  },
  errorBoundaryMessage: {
    color: "#dc2626",
    fontSize: "14px",
    marginTop: "4px",
  },
  errorBoundaryButton: {
    marginTop: "8px",
    fontSize: "14px",
    color: "#b91c1c",
    backgroundColor: "transparent",
    border: "none",
    cursor: "pointer",
  },
};
